path:
  root_dir: /project/jens/wAEvplus3.p
  raw_dir: ${path.root_dir}/data_raw/LibriSpeech
  preprocessed_dir: ${path.root_dir}/preprocessed
  csv: ${path.preprocessed_dir}/corpus.csv
  array_dir: ${path.preprocessed_dir}/raw_np
  vocab: ${path.preprocessed_dir}/vocab.txt
  model: ${path.root_dir}/models/best.h5
  logs: ${path.root_dir}/logs

features:
  mel_freqs: 128
  window_size: 512
  hop_length: 128
  normalize: False
  resample_rate: 0
  sample_rate: 16000

training:
  batch_size: 16
  learning_rate: 0.0001
  weight_decay: 0.0001
  warmup_epochs: 1
  steps_per_epoch: 5000
  epochs: 60
