path:
  raw_dir: /project/jens/wAEvplus3.p/data_raw/LibriSpeech
  root_dir: /project/jens/wAEvplus3.p/preprocessed
  csv: ${path.root_dir}/corpus.csv
  array_dir: ${path.root_dir}/raw_np
  vocab: ${path.root_dir}/vocab.txt

features:
  mel_freqs: 128
  window_size: 512
  hop_length: 128
  normalize: False
  resample_rate: 0
  sample_rate: 16000

training:
  batch_size: 16
  learning_rate: 0.001
  epochs: 2000